/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutStoresRouteImport } from './routes/_layout/stores'
import { Route as LayoutStaffRouteImport } from './routes/_layout/staff'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReviewRouteImport } from './routes/_layout/review'
import { Route as LayoutRequestsRouteImport } from './routes/_layout/requests'
import { Route as LayoutQualificationsRouteImport } from './routes/_layout/qualifications'
import { Route as LayoutProfilesRouteImport } from './routes/_layout/profiles'
import { Route as LayoutMembersRouteImport } from './routes/_layout/members'
import { Route as LayoutFeedbackRouteImport } from './routes/_layout/feedback'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutMembersUserIdRouteImport } from './routes/_layout/members.$userId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutStoresRoute = LayoutStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStaffRoute = LayoutStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewRoute = LayoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRequestsRoute = LayoutRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQualificationsRoute = LayoutQualificationsRouteImport.update({
  id: '/qualifications',
  path: '/qualifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfilesRoute = LayoutProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersRoute = LayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedbackRoute = LayoutFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersUserIdRoute = LayoutMembersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => LayoutMembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/members': typeof LayoutMembersRouteWithChildren
  '/profiles': typeof LayoutProfilesRoute
  '/qualifications': typeof LayoutQualificationsRoute
  '/requests': typeof LayoutRequestsRoute
  '/review': typeof LayoutReviewRoute
  '/settings': typeof LayoutSettingsRoute
  '/staff': typeof LayoutStaffRoute
  '/stores': typeof LayoutStoresRoute
  '/members/$userId': typeof LayoutMembersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/members': typeof LayoutMembersRouteWithChildren
  '/profiles': typeof LayoutProfilesRoute
  '/qualifications': typeof LayoutQualificationsRoute
  '/requests': typeof LayoutRequestsRoute
  '/review': typeof LayoutReviewRoute
  '/settings': typeof LayoutSettingsRoute
  '/staff': typeof LayoutStaffRoute
  '/stores': typeof LayoutStoresRoute
  '/members/$userId': typeof LayoutMembersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/feedback': typeof LayoutFeedbackRoute
  '/_layout/members': typeof LayoutMembersRouteWithChildren
  '/_layout/profiles': typeof LayoutProfilesRoute
  '/_layout/qualifications': typeof LayoutQualificationsRoute
  '/_layout/requests': typeof LayoutRequestsRoute
  '/_layout/review': typeof LayoutReviewRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/staff': typeof LayoutStaffRoute
  '/_layout/stores': typeof LayoutStoresRoute
  '/_layout/members/$userId': typeof LayoutMembersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/feedback'
    | '/members'
    | '/profiles'
    | '/qualifications'
    | '/requests'
    | '/review'
    | '/settings'
    | '/staff'
    | '/stores'
    | '/members/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/feedback'
    | '/members'
    | '/profiles'
    | '/qualifications'
    | '/requests'
    | '/review'
    | '/settings'
    | '/staff'
    | '/stores'
    | '/members/$userId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/dashboard'
    | '/_layout/feedback'
    | '/_layout/members'
    | '/_layout/profiles'
    | '/_layout/qualifications'
    | '/_layout/requests'
    | '/_layout/review'
    | '/_layout/settings'
    | '/_layout/staff'
    | '/_layout/stores'
    | '/_layout/members/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/stores': {
      id: '/_layout/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof LayoutStoresRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/staff': {
      id: '/_layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof LayoutStaffRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/review': {
      id: '/_layout/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof LayoutReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/requests': {
      id: '/_layout/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof LayoutRequestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/qualifications': {
      id: '/_layout/qualifications'
      path: '/qualifications'
      fullPath: '/qualifications'
      preLoaderRoute: typeof LayoutQualificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profiles': {
      id: '/_layout/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof LayoutProfilesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members': {
      id: '/_layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof LayoutMembersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feedback': {
      id: '/_layout/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof LayoutFeedbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members/$userId': {
      id: '/_layout/members/$userId'
      path: '/$userId'
      fullPath: '/members/$userId'
      preLoaderRoute: typeof LayoutMembersUserIdRouteImport
      parentRoute: typeof LayoutMembersRoute
    }
  }
}

interface LayoutMembersRouteChildren {
  LayoutMembersUserIdRoute: typeof LayoutMembersUserIdRoute
}

const LayoutMembersRouteChildren: LayoutMembersRouteChildren = {
  LayoutMembersUserIdRoute: LayoutMembersUserIdRoute,
}

const LayoutMembersRouteWithChildren = LayoutMembersRoute._addFileChildren(
  LayoutMembersRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutFeedbackRoute: typeof LayoutFeedbackRoute
  LayoutMembersRoute: typeof LayoutMembersRouteWithChildren
  LayoutProfilesRoute: typeof LayoutProfilesRoute
  LayoutQualificationsRoute: typeof LayoutQualificationsRoute
  LayoutRequestsRoute: typeof LayoutRequestsRoute
  LayoutReviewRoute: typeof LayoutReviewRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStaffRoute: typeof LayoutStaffRoute
  LayoutStoresRoute: typeof LayoutStoresRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutFeedbackRoute: LayoutFeedbackRoute,
  LayoutMembersRoute: LayoutMembersRouteWithChildren,
  LayoutProfilesRoute: LayoutProfilesRoute,
  LayoutQualificationsRoute: LayoutQualificationsRoute,
  LayoutRequestsRoute: LayoutRequestsRoute,
  LayoutReviewRoute: LayoutReviewRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStaffRoute: LayoutStaffRoute,
  LayoutStoresRoute: LayoutStoresRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
