const profiles = [
  {
    id: '53366922',
    gender: '女',
    year: 1987,
    age: 39,
    height: 163,
    edu: '小学/初中',
    origin: '天津',
    location: '德州',
    job: '国企员工',
    income: '3-5万',
    marriage: '离异已育',
    hasHouse: '有婚房',
    bodyType: '适中',
    hometown: '德州',
    likes: 0,
    hot: 116,
    posted: '3天前',
    desc: '我家女儿，出生于87年，身高163厘米，学历小学/初中，目前居住在德州，职业国企员工，踏实顾家，希望对方稳重可靠，欢迎和我联系。',
    wants: {
      year: '1982年-1987年',
      income: '不限',
      height: '170cm-188cm',
      house: '不限',
      edu: '中专/高中及以上',
      marriage: '离异未育',
      origin: '德州',
      location: '德州',
    },
    tone: 'rose',
    glyph: '寻',
  },
  {
    id: '31821616',
    gender: '女',
    year: 1991,
    age: 35,
    height: 160,
    edu: '小学/初中',
    origin: '德州',
    location: '德州德城区',
    job: '销售',
    income: '5-7万',
    marriage: '未婚',
    hasHouse: '无婚房',
    bodyType: '匀称',
    hometown: '德州',
    likes: 12,
    hot: 204,
    posted: '1天前',
    desc: '我家女儿，出生于91年，身高160厘米，学历小学/初中，目前居住在德州德城区，职业销售，性格开朗，希望找个踏实的人。',
    wants: {
      year: '1985年-1991年',
      income: '5-7万以上',
      height: '168cm-185cm',
      house: '有婚房',
      edu: '不限',
      marriage: '未婚',
      origin: '德州',
      location: '德州',
    },
    tone: 'sage',
    glyph: '缘',
  },
  {
    id: '47291038',
    gender: '男',
    year: 1989,
    age: 37,
    height: 175,
    edu: '本科',
    origin: '淄博桓台县',
    location: '北京东城区',
    job: '软件开发工程师',
    income: '30-50万',
    marriage: '未婚',
    hasHouse: '有婚房',
    bodyType: '偏瘦',
    hometown: '淄博',
    likes: 28,
    hot: 389,
    posted: '今天',
    desc: '我儿子，89年出生，身高175厘米，本科毕业，目前在北京工作，软件工程师，性格温和顾家，希望找一位善良贤惠的姑娘。',
    wants: {
      year: '1988年-1995年',
      income: '不限',
      height: '158cm-170cm',
      house: '不限',
      edu: '本科',
      marriage: '未婚',
      origin: '不限',
      location: '北京',
    },
    tone: 'ocean',
    glyph: '乾',
  },
  {
    id: '68402957',
    gender: '男',
    year: 1985,
    age: 41,
    height: 178,
    edu: '大专',
    origin: '河北石家庄',
    location: '北京朝阳区',
    job: '公务员',
    income: '15-20万',
    marriage: '离异未育',
    hasHouse: '有婚房',
    bodyType: '中等',
    hometown: '石家庄',
    likes: 19,
    hot: 267,
    posted: '2天前',
    desc: '我侄子，85年出生，178厘米，公务员，人踏实上进，离异未育，希望重新寻找合适的另一半，诚心以待。',
    wants: {
      year: '1987年-1995年',
      income: '不限',
      height: '160cm-172cm',
      house: '不限',
      edu: '大专',
      marriage: '未婚',
      origin: '不限',
      location: '北京',
    },
    tone: 'indigo',
    glyph: '合',
  },
  {
    id: '29475861',
    gender: '女',
    year: 1993,
    age: 33,
    height: 166,
    edu: '本科',
    origin: '山东济南',
    location: '济南历下区',
    job: '教师',
    income: '7-10万',
    marriage: '未婚',
    hasHouse: '无婚房',
    bodyType: '苗条',
    hometown: '济南',
    likes: 47,
    hot: 512,
    posted: '今天',
    desc: '我女儿，93年出生，166厘米，本科毕业，小学教师，性格温柔文静，喜欢阅读与烘焙，希望对方成熟稳重、有责任心。',
    wants: {
      year: '1988年-1993年',
      income: '10万以上',
      height: '172cm-185cm',
      house: '有婚房',
      edu: '本科',
      marriage: '未婚',
      origin: '山东',
      location: '济南',
    },
    tone: 'plum',
    glyph: '雅',
  },
  {
    id: '81937465',
    gender: '女',
    year: 1990,
    age: 36,
    height: 162,
    edu: '中专/高中',
    origin: '江苏徐州',
    location: '徐州云龙区',
    job: '银行职员',
    income: '10-15万',
    marriage: '未婚',
    hasHouse: '有婚房',
    bodyType: '适中',
    hometown: '徐州',
    likes: 33,
    hot: 412,
    posted: '2天前',
    desc: '我家闺女，90年，162，徐州本地人，银行工作稳定，人长得秀气，性格温婉，希望另一半成熟踏实，最好本地或周边。',
    wants: {
      year: '1985年-1990年',
      income: '15万以上',
      height: '170cm-183cm',
      house: '有婚房',
      edu: '本科',
      marriage: '未婚',
      origin: '江苏',
      location: '徐州',
    },
    tone: 'gold',
    glyph: '良',
  },
];

const eduOptions = ['不限', '小学/初中', '中专/高中', '大专', '本科', '硕士', '博士及以上'];
const incomeOptions = ['不限', '3万以下', '3-5万', '5-7万', '7-10万', '10-15万', '15-20万', '20-30万', '30-50万', '50-100万', '100万以上'];
const houseOptions = ['不限', '有婚房', '无婚房', '有购房计划'];
const marriageOptions = ['不限', '未婚', '离异未育', '离异已育'];
const jobOptions = ['公务员', '会计', '国企员工', '销售', '事业单位', '建筑工程师', '教师', '律师', '医生', '银行职员', '护士', '军人', '软件开发工程师', '个体经营者', '设计师', '金融从业者', '自由职业者', '互联网职员', '央企员工', '公共服务人员'];
const regions = ['北京', '天津', '山东', '河北', '江苏', '上海', '济南', '德州', '青岛', '徐州', '苏州', '杭州'];
const traits = ['孝顺', '成熟', '谦虚', '幽默', '热情', '温文尔雅', '踏实', '细心', '开朗', '真诚', '正直', '顾家'];
const advantages = ['有上进心', '有车', '家教好', '家乡有房', '会做家务', '不抽烟喝酒', '收入稳定', '身体健康', '学历高', '工作稳定'];
const requirements = ['本地优先', '收入稳定', '体贴', '学历相符', '门当户对', '顾家', '性格温和', '身高相符', '无不良嗜好', '孝顺父母'];

module.exports = {
  profiles,
  eduOptions,
  incomeOptions,
  houseOptions,
  marriageOptions,
  jobOptions,
  regions,
  traits,
  advantages,
  requirements,
};
