// This file is auto-generated by @hey-api/openapi-ts

export type ActivityItem = {
    counterpart_user_id: string;
    xy_code?: (string | null);
    nickname?: (string | null);
    avatar_url?: (string | null);
    created_at: string;
};

export type ActivityList = {
    items?: Array<ActivityItem>;
    total?: number;
};

export type AdminContactRequestItem = {
    id: string;
    from_user_id: string;
    from_xy_code?: (string | null);
    from_gender?: (string | null);
    from_year?: (number | null);
    from_location?: (string | null);
    from_contact_wechat?: (string | null);
    from_contact_phone?: (string | null);
    to_user_id: string;
    to_xy_code?: (string | null);
    to_gender?: (string | null);
    to_year?: (number | null);
    to_location?: (string | null);
    to_contact_wechat?: (string | null);
    to_contact_phone?: (string | null);
    message?: (string | null);
    status: string;
    admin_note?: (string | null);
    handled_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type AdminContactRequestList = {
    items?: Array<AdminContactRequestItem>;
    total?: number;
};

export type AdminCriteriaItem = {
    user_id: string;
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    weight_min?: (number | null);
    weight_max?: (number | null);
    income?: (string | null);
    edu?: (string | null);
    marriage?: (string | null);
    house?: (string | null);
    car?: (string | null);
    job?: (string | null);
    social_insurance?: (string | null);
    note?: (string | null);
    origins?: Array<(string)>;
    locations?: Array<(string)>;
    progress?: number;
};

export type AdminCriteriaUpdate = {
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    weight_min?: (number | null);
    weight_max?: (number | null);
    income?: (string | null);
    edu?: (string | null);
    marriage?: (string | null);
    house?: (string | null);
    car?: (string | null);
    job?: (string | null);
    social_insurance?: (string | null);
    note?: (string | null);
    origins?: (Array<(string)> | null);
    locations?: (Array<(string)> | null);
};

export type AdminFeedbackItem = {
    id: string;
    user_id: string;
    user_xy_code?: (string | null);
    content: string;
    contact?: (string | null);
    status: string;
    created_at: string;
};

export type AdminFeedbackList = {
    items?: Array<AdminFeedbackItem>;
    total?: number;
};

/**
 * 会员 360° 聚合: 一次请求拿全 (前端详情页专用).
 */
export type AdminMemberFull = {
    member: AdminMemberItem;
    profile?: (AdminProfileItem | null);
    criteria?: (AdminCriteriaItem | null);
    parents_info?: (AdminParentsInfoItem | null);
    home_store_name?: (string | null);
    verified_by_store_id?: (string | null);
    verified_at?: (string | null);
    counts?: MemberCounts;
    can_view_contact?: boolean;
};

/**
 * 会员列表行: User + Profile 摘要 (不含联系方式).
 */
export type AdminMemberItem = {
    user_id: string;
    xy_code?: (string | null);
    nickname?: (string | null);
    real_name?: (string | null);
    avatar_url?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    birth_date?: (string | null);
    relation?: (string | null);
    location?: (string | null);
    home_store_id?: (string | null);
    audit_status?: (string | null);
    progress?: number;
    verified?: string;
    unlock_balance?: number;
    user_status?: string;
    last_active_at?: (string | null);
    created_at: string;
};

export type AdminMemberList = {
    items?: Array<AdminMemberItem>;
    total?: number;
};

export type AdminParentsInfoItem = {
    user_id: string;
    parents_health?: (string | null);
    parents_job?: (string | null);
    parents_pension?: (string | null);
    siblings?: (string | null);
};

export type AdminParentsInfoUpdate = {
    parents_health?: (string | null);
    parents_job?: (string | null);
    parents_pension?: (string | null);
    siblings?: (string | null);
};

/**
 * 资料详情 + 择偶要求 + 父母信息 (admin 视角, 含联系方式)
 */
export type AdminProfileDetail = {
    profile: AdminProfileItem;
    criteria?: (AdminCriteriaItem | null);
    parents_info?: (AdminParentsInfoItem | null);
};

export type AdminProfileItem = {
    user_id: string;
    xy_code?: (string | null);
    openid?: (string | null);
    nickname?: (string | null);
    avatar_url?: (string | null);
    real_name?: (string | null);
    ethnicity?: (string | null);
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    birth_date?: (string | null);
    height?: (number | null);
    weight?: (number | null);
    health_status?: (string | null);
    edu?: (string | null);
    major?: (string | null);
    hobbies?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    employer_type?: (string | null);
    has_social_insurance?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    house_car_loan?: (string | null);
    body_type?: (string | null);
    personality_type?: (string | null);
    desc?: (string | null);
    photos?: Array<(string)>;
    contact_wechat?: (string | null);
    contact_phone?: (string | null);
    audit_status: string;
    audit_reason?: (string | null);
    progress?: number;
    likes?: number;
    hot?: number;
    viewed_count?: number;
    unlock_balance?: number;
    verified?: string;
    user_status?: string;
    last_active_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type AdminProfileList = {
    items?: Array<AdminProfileItem>;
    total?: number;
};

/**
 * 红娘代录: 任意字段都可单独更新, 不传不动. 含敏感联系方式.
 */
export type AdminProfileUpdate = {
    nickname?: (string | null);
    avatar_url?: (string | null);
    real_name?: (string | null);
    ethnicity?: (string | null);
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    birth_date?: (string | null);
    height?: (number | null);
    weight?: (number | null);
    health_status?: (string | null);
    edu?: (string | null);
    major?: (string | null);
    hobbies?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    employer_type?: (string | null);
    has_social_insurance?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    house_car_loan?: (string | null);
    body_type?: (string | null);
    personality_type?: (string | null);
    desc?: (string | null);
    contact_wechat?: (string | null);
    contact_phone?: (string | null);
};

export type AdminUserBrief = {
    id: string;
    openid?: (string | null);
    xy_code?: (string | null);
    email?: (string | null);
    is_superuser?: boolean;
    unlock_balance?: number;
    status?: string;
    last_active_at?: (string | null);
    created_at: string;
};

export type AdminUserItem = {
    id: string;
    actor: string;
    xy_code?: (string | null);
    openid?: (string | null);
    email?: (string | null);
    full_name?: (string | null);
    is_superuser?: boolean;
    unlock_balance?: number;
    notify_enabled?: boolean;
    verified?: string;
    status?: string;
    last_active_at?: (string | null);
    created_at: string;
};

export type AdminUserList = {
    items?: Array<AdminUserItem>;
    total?: number;
};

export type AffinityBrief = {
    user_id: string;
    xy_code?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    location?: (string | null);
    photos?: Array<(string)>;
    affinity_at: string;
    is_mutual?: boolean;
};

export type AffinityList = {
    items?: Array<AffinityBrief>;
    total?: number;
};

export type AffinityToggleResponse = {
    liked: boolean;
    mutual: boolean;
    created_at?: (string | null);
};

export type AuditLogList = {
    items?: Array<AuditLogPublic>;
    total?: number;
};

export type AuditLogPublic = {
    id: string;
    actor_type: string;
    actor_id: string;
    actor_email?: (string | null);
    action: string;
    target_user_id?: (string | null);
    detail?: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type AuditRequest = {
    approve?: boolean;
    reason?: (string | null);
};

export type BalanceTransactionList = {
    items?: Array<BalanceTransactionPublic>;
    total?: number;
};

export type BalanceTransactionPublic = {
    id: string;
    user_id: string;
    amount: number;
    balance_after: number;
    source: string;
    ref_id?: (string | null);
    note?: (string | null);
    created_at: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_profiles_update_my_contact = {
    wechat?: (string | null);
    phone?: (string | null);
};

export type Body_uploads_upload_image = {
    file: (Blob | File);
};

export type CityItem = {
    city: string;
    count: number;
};

export type CityList = {
    items?: Array<CityItem>;
};

export type ContactRequestBody = {
    target_user_id: string;
    message?: (string | null);
};

export type ContactRequestList = {
    items?: Array<ContactRequestPublic>;
    total?: number;
};

/**
 * 用户视角: 看自己提交过的申请
 */
export type ContactRequestPublic = {
    id: string;
    from_user_id: string;
    to_user_id: string;
    target_xy_code?: (string | null);
    message?: (string | null);
    status: string;
    admin_note?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ContactRequestResult = {
    request_id: string;
    balance: number;
    status: string;
    created_at: string;
};

export type ContactViewResponse = {
    contact_wechat?: (string | null);
    contact_phone?: (string | null);
};

export type CriteriaPublic = {
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    weight_min?: (number | null);
    weight_max?: (number | null);
    income?: (string | null);
    edu?: (string | null);
    marriage?: (string | null);
    house?: (string | null);
    car?: (string | null);
    job?: (string | null);
    social_insurance?: (string | null);
    note?: (string | null);
    id: string;
    user_id: string;
    origins?: Array<(string)>;
    locations?: Array<(string)>;
    progress?: number;
};

export type CriteriaUpdate = {
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    weight_min?: (number | null);
    weight_max?: (number | null);
    income?: (string | null);
    edu?: (string | null);
    marriage?: (string | null);
    house?: (string | null);
    car?: (string | null);
    job?: (string | null);
    social_insurance?: (string | null);
    note?: (string | null);
    origins?: (Array<(string)> | null);
    locations?: (Array<(string)> | null);
};

export type FavoriteBrief = {
    user_id: string;
    xy_code?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    location?: (string | null);
    photos?: Array<(string)>;
    starred_at: string;
};

export type FavoriteList = {
    items?: Array<FavoriteBrief>;
    total?: number;
};

export type FeedbackBody = {
    content: string;
    contact?: (string | null);
};

export type FeedbackResponse = {
    id: string;
    created_at: string;
};

export type FilterRequest = {
    gender?: (string | null);
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    edu?: (Array<(string)> | null);
    income?: (Array<(string)> | null);
    marriage?: (Array<(string)> | null);
    region?: (Array<(string)> | null);
    job?: (Array<(string)> | null);
    has_house?: (Array<(string)> | null);
    cursor?: (string | null);
    limit?: number;
};

export type GrantBalanceRequest = {
    delta?: number;
    reason?: (string | null);
};

export type HandleRequestBody = {
    status: 'accepted' | 'rejected' | 'contacted' | 'closed';
    admin_note?: (string | null);
};

export type status = 'accepted' | 'rejected' | 'contacted' | 'closed';

export type HomeStoreBody = {
    store_id: string;
};

export type HomeStoreUpdate = {
    store_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * 列表项 - 不含联系方式 / desc 截断
 */
export type MatchBrief = {
    user_id: string;
    xy_code?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    edu?: (string | null);
    income?: (string | null);
    location?: (string | null);
    origin?: (string | null);
    desc?: (string | null);
    photos?: Array<(string)>;
    likes?: number;
    hot?: number;
    starred?: boolean;
    verified?: string;
};

export type MatchDetailResponse = {
    profile: ProfilePublic;
    xy_code?: (string | null);
    unlocked?: boolean;
    starred?: boolean;
    verified?: string;
};

export type MatchListResponse = {
    items?: Array<MatchBrief>;
    next_cursor?: (string | null);
};

export type MemberCounts = {
    favorites_given?: number;
    favorites_received?: number;
    views_given?: number;
    views_received?: number;
    affinity_given?: number;
    affinity_received?: number;
    requests_sent?: number;
    requests_received?: number;
};

export type Message = {
    message: string;
};

export type NeighborResponse = {
    user_id?: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ParentsInfoPublic = {
    parents_health?: (string | null);
    parents_job?: (string | null);
    parents_pension?: (string | null);
    siblings?: (string | null);
    user_id: string;
};

export type PhotoCommit = {
    file_url: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfileMeResponse = {
    profile?: (ProfileWithContact | null);
    criteria?: (CriteriaPublic | null);
    parents_info?: (ParentsInfoPublic | null);
    home_store?: (StorePublic | null);
    verified?: string;
    home_store_id?: (string | null);
    has_profile?: boolean;
    has_criteria?: boolean;
    is_welcomed?: boolean;
};

export type ProfilePublic = {
    nickname?: (string | null);
    avatar_url?: (string | null);
    real_name?: (string | null);
    ethnicity?: (string | null);
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    birth_date?: (string | null);
    height?: (number | null);
    weight?: (number | null);
    health_status?: (string | null);
    edu?: (string | null);
    major?: (string | null);
    hobbies?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    employer_type?: (string | null);
    has_social_insurance?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    house_car_loan?: (string | null);
    body_type?: (string | null);
    personality_type?: (string | null);
    desc?: (string | null);
    id: string;
    user_id: string;
    photos?: Array<(string)>;
    audit_status?: string;
    progress?: number;
    likes?: number;
    hot?: number;
    viewed_count?: number;
};

/**
 * 允许部分更新
 */
export type ProfileUpdate = {
    nickname?: (string | null);
    avatar_url?: (string | null);
    real_name?: (string | null);
    ethnicity?: (string | null);
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    birth_date?: (string | null);
    height?: (number | null);
    weight?: (number | null);
    health_status?: (string | null);
    edu?: (string | null);
    major?: (string | null);
    hobbies?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    employer_type?: (string | null);
    has_social_insurance?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    house_car_loan?: (string | null);
    body_type?: (string | null);
    personality_type?: (string | null);
    desc?: (string | null);
};

/**
 * 已解锁/管理员视角, 含联系方式
 */
export type ProfileWithContact = {
    nickname?: (string | null);
    avatar_url?: (string | null);
    real_name?: (string | null);
    ethnicity?: (string | null);
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    birth_date?: (string | null);
    height?: (number | null);
    weight?: (number | null);
    health_status?: (string | null);
    edu?: (string | null);
    major?: (string | null);
    hobbies?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    employer_type?: (string | null);
    has_social_insurance?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    house_car_loan?: (string | null);
    body_type?: (string | null);
    personality_type?: (string | null);
    desc?: (string | null);
    id: string;
    user_id: string;
    photos?: Array<(string)>;
    audit_status?: string;
    progress?: number;
    likes?: number;
    hot?: number;
    viewed_count?: number;
    contact_wechat?: (string | null);
    contact_phone?: (string | null);
};

export type QualificationItem = {
    image_url: string;
    title?: (string | null);
};

export type QualificationList = {
    items?: Array<QualificationItem>;
};

export type StaffCreate = {
    email: string;
    name: string;
    is_active?: boolean;
    role?: string;
    store_id?: (string | null);
    password: string;
};

export type StaffPublic = {
    email: string;
    name: string;
    is_active?: boolean;
    role?: string;
    store_id?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type StaffsPublic = {
    items?: Array<StaffPublic>;
    total?: number;
};

export type StaffUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
    password?: (string | null);
    role?: (string | null);
    store_id?: (string | null);
};

export type StatsResponse = {
    total_users?: number;
    total_profiles?: number;
    pending_audits?: number;
    today_signups?: number;
    pending_tickets?: number;
    mutual_affinity_pairs?: number;
    verified_users?: number;
    verified_ratio?: number;
    active_stores?: number;
    pending_verifies?: number;
    open_feedback?: number;
};

export type StoreCreate = {
    name: string;
    city: string;
    district?: (string | null);
    address?: (string | null);
    lng?: (number | null);
    lat?: (number | null);
    phone?: (string | null);
    photo?: (string | null);
    fees_desc?: (string | null);
    status?: string;
};

export type StoreList = {
    items?: Array<StorePublic>;
    total?: number;
};

export type StorePublic = {
    name: string;
    city: string;
    district?: (string | null);
    address?: (string | null);
    lng?: (number | null);
    lat?: (number | null);
    phone?: (string | null);
    photo?: (string | null);
    fees_desc?: (string | null);
    status?: string;
    id: string;
};

export type StoreUpdate = {
    name?: (string | null);
    city?: (string | null);
    district?: (string | null);
    address?: (string | null);
    lng?: (number | null);
    lat?: (number | null);
    phone?: (string | null);
    photo?: (string | null);
    fees_desc?: (string | null);
    status?: (string | null);
};

export type ToggleResponse = {
    starred: boolean;
    total_likes: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UploadResponse = {
    url: string;
    filename: string;
    size: number;
};

/**
 * admin 创建账号 (邮箱密码)
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    xy_code?: (string | null);
    unlock_balance?: number;
    notify_enabled?: boolean;
    verified?: string;
};

/**
 * 邮箱自助注册
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VerifyResponse = {
    user_id: string;
    verified: string;
    verified_by_store_id?: (string | null);
    verified_at?: (string | null);
};

export type VisitorBrief = {
    user_id: string;
    xy_code?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    photos?: Array<(string)>;
    last_viewed_at: string;
};

export type VisitorList = {
    items?: Array<VisitorBrief>;
    total?: number;
};

export type WechatLoginRequest = {
    code: string;
};

export type WechatLoginResponse = {
    access_token: string;
    token_type?: string;
    user: UserPublic;
    has_profile?: boolean;
    has_criteria?: boolean;
    is_welcomed?: boolean;
};

export type WelcomeBody = {
    nickname: string;
    avatar_url: string;
};

/**
 * 统一的"当前登录者"返回, 兼容 User (含 superuser) 和 Staff
 */
export type WhoAmI = {
    id: string;
    actor_type: string;
    email?: (string | null);
    name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    can_read_admin?: boolean;
    can_write_admin?: boolean;
};

export type AdminListProfilesData = {
    auditStatus?: 'all' | 'pending' | 'approved' | 'rejected';
    /**
     * 搜寻缘号 / 居住地 / desc
     */
    keyword?: (string | null);
    limit?: number;
    skip?: number;
};

export type AdminListProfilesResponse = (AdminProfileList);

export type AdminGetProfileDetailData = {
    userId: string;
};

export type AdminGetProfileDetailResponse = (AdminProfileDetail);

export type AdminAuditProfileData = {
    requestBody: AuditRequest;
    userId: string;
};

export type AdminAuditProfileResponse = (AdminProfileItem);

export type AdminAdminUpdateProfileData = {
    requestBody: AdminProfileUpdate;
    userId: string;
};

export type AdminAdminUpdateProfileResponse = (AdminProfileItem);

export type AdminAdminUpdateCriteriaData = {
    requestBody: AdminCriteriaUpdate;
    userId: string;
};

export type AdminAdminUpdateCriteriaResponse = (AdminCriteriaItem);

export type AdminAdminUpdateParentsInfoData = {
    requestBody: AdminParentsInfoUpdate;
    userId: string;
};

export type AdminAdminUpdateParentsInfoResponse = (AdminParentsInfoItem);

export type AdminVerifyProfileData = {
    userId: string;
};

export type AdminVerifyProfileResponse = (VerifyResponse);

export type AdminUnverifyProfileData = {
    userId: string;
};

export type AdminUnverifyProfileResponse = (VerifyResponse);

export type AdminAdminSetHomeStoreData = {
    requestBody: HomeStoreUpdate;
    userId: string;
};

export type AdminAdminSetHomeStoreResponse = (AdminProfileItem);

export type AdminAdminListStoresData = {
    city?: (string | null);
    limit?: number;
    skip?: number;
};

export type AdminAdminListStoresResponse = (StoreList);

export type AdminAdminCreateStoreData = {
    requestBody: StoreCreate;
};

export type AdminAdminCreateStoreResponse = (StorePublic);

export type AdminAdminUpdateStoreData = {
    requestBody: StoreUpdate;
    storeId: string;
};

export type AdminAdminUpdateStoreResponse = (StorePublic);

export type AdminAdminDeleteStoreData = {
    storeId: string;
};

export type AdminAdminDeleteStoreResponse = (Message);

export type AdminAdminListFeedbackData = {
    limit?: number;
    skip?: number;
};

export type AdminAdminListFeedbackResponse = (AdminFeedbackList);

export type AdminGrantUnlockBalanceData = {
    requestBody: GrantBalanceRequest;
    userId: string;
};

export type AdminGrantUnlockBalanceResponse = (AdminUserBrief);

export type AdminBlockUserData = {
    userId: string;
};

export type AdminBlockUserResponse = (AdminUserBrief);

export type AdminUnblockUserData = {
    userId: string;
};

export type AdminUnblockUserResponse = (AdminUserBrief);

export type AdminAdminStatsResponse = (StatsResponse);

export type AdminListAdminUsersData = {
    actor?: 'all' | 'wx' | 'admin';
    keyword?: (string | null);
    limit?: number;
    skip?: number;
    userStatus?: 'all' | 'active' | 'inactive' | 'deactivating' | 'blocked';
};

export type AdminListAdminUsersResponse = (AdminUserList);

export type AdminListStaffData = {
    limit?: number;
    skip?: number;
};

export type AdminListStaffResponse = (StaffsPublic);

export type AdminCreateStaffEndpointData = {
    requestBody: StaffCreate;
};

export type AdminCreateStaffEndpointResponse = (StaffPublic);

export type AdminUpdateStaffEndpointData = {
    requestBody: StaffUpdate;
    staffId: string;
};

export type AdminUpdateStaffEndpointResponse = (StaffPublic);

export type AdminDeleteStaffEndpointData = {
    staffId: string;
};

export type AdminDeleteStaffEndpointResponse = (Message);

export type AdminListContactRequestsData = {
    limit?: number;
    skip?: number;
    status?: 'all' | 'pending' | 'accepted' | 'rejected' | 'contacted' | 'closed';
};

export type AdminListContactRequestsResponse = (AdminContactRequestList);

export type AdminHandleContactRequestData = {
    requestBody: HandleRequestBody;
    requestId: string;
};

export type AdminHandleContactRequestResponse = (AdminContactRequestItem);

export type AdminListMembersData = {
    auditStatus?: 'all' | 'none' | 'pending' | 'approved' | 'rejected';
    gender?: (string | null);
    /**
     * 寻缘号 / 姓名 / 昵称 / 手机号
     */
    keyword?: (string | null);
    limit?: number;
    skip?: number;
    storeId?: (string | null);
    userStatus?: 'all' | 'active' | 'blocked';
    verified?: 'all' | 'none' | 'pending' | 'passed' | 'rejected';
};

export type AdminListMembersResponse = (AdminMemberList);

export type AdminGetMemberFullData = {
    userId: string;
};

export type AdminGetMemberFullResponse = (AdminMemberFull);

export type AdminViewMemberContactData = {
    userId: string;
};

export type AdminViewMemberContactResponse = (ContactViewResponse);

export type AdminListMemberTransactionsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type AdminListMemberTransactionsResponse = (BalanceTransactionList);

export type AdminListMemberActivitiesData = {
    kind?: 'favorite_given' | 'favorite_received' | 'view_given' | 'view_received' | 'affinity_given' | 'affinity_received';
    limit?: number;
    skip?: number;
    userId: string;
};

export type AdminListMemberActivitiesResponse = (ActivityList);

export type AdminListMemberRequestsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type AdminListMemberRequestsResponse = (AdminContactRequestList);

export type AdminListMemberAuditLogsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type AdminListMemberAuditLogsResponse = (AuditLogList);

export type AdminListAuditLogsData = {
    action?: (string | null);
    limit?: number;
    skip?: number;
    targetUserId?: (string | null);
};

export type AdminListAuditLogsResponse = (AuditLogList);

export type AdminListVerifyQueueData = {
    limit?: number;
    skip?: number;
};

export type AdminListVerifyQueueResponse = (AdminMemberList);

export type AffinityToggleAffinityData = {
    targetUserId: string;
};

export type AffinityToggleAffinityResponse = (AffinityToggleResponse);

export type AffinityListMineData = {
    limit?: number;
    skip?: number;
};

export type AffinityListMineResponse = (AffinityList);

export type AffinityListMutualData = {
    limit?: number;
    skip?: number;
};

export type AffinityListMutualResponse = (AffinityList);

export type AffinityCheckAffinityData = {
    targetUserId: string;
};

export type AffinityCheckAffinityResponse = (AffinityToggleResponse);

export type ContactsSubmitContactRequestData = {
    requestBody: ContactRequestBody;
};

export type ContactsSubmitContactRequestResponse = (ContactRequestResult);

export type ContactsListMyContactRequestsData = {
    limit?: number;
    skip?: number;
};

export type ContactsListMyContactRequestsResponse = (ContactRequestList);

export type ContactsUnlockContactDeprecatedData = {
    targetId: string;
};

export type ContactsUnlockContactDeprecatedResponse = (unknown);

export type FavoritesToggleFavoriteData = {
    targetId: string;
};

export type FavoritesToggleFavoriteResponse = (ToggleResponse);

export type FavoritesListMyFavoritesData = {
    limit?: number;
    skip?: number;
};

export type FavoritesListMyFavoritesResponse = (FavoriteList);

export type FavoritesListVisitorsData = {
    limit?: number;
    skip?: number;
};

export type FavoritesListVisitorsResponse = (VisitorList);

export type FavoritesListSeenByMeData = {
    limit?: number;
    skip?: number;
};

export type FavoritesListSeenByMeResponse = (VisitorList);

export type FeedbackSubmitFeedbackData = {
    requestBody: FeedbackBody;
};

export type FeedbackSubmitFeedbackResponse = (FeedbackResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginWhoamiResponse = (WhoAmI);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MatchesGetDailyRecommendationsData = {
    cursor?: (string | null);
    limit?: number;
    tab?: 'today' | 'new' | 'missed';
};

export type MatchesGetDailyRecommendationsResponse = (MatchListResponse);

export type MatchesApplyFilterData = {
    requestBody: FilterRequest;
};

export type MatchesApplyFilterResponse = (MatchListResponse);

export type MatchesGetProfileDetailData = {
    userId: string;
};

export type MatchesGetProfileDetailResponse = (MatchDetailResponse);

export type MatchesGetNeighborData = {
    direction?: 'prev' | 'next';
    userId: string;
};

export type MatchesGetNeighborResponse = (NeighborResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfilesReadMyProfileResponse = (ProfileMeResponse);

export type ProfilesUpsertMyProfileData = {
    requestBody: ProfileUpdate;
};

export type ProfilesUpsertMyProfileResponse = (ProfileWithContact);

export type ProfilesDeleteMyProfileResponse = (Message);

export type ProfilesSubmitWelcomeData = {
    requestBody: WelcomeBody;
};

export type ProfilesSubmitWelcomeResponse = (ProfileWithContact);

export type ProfilesUpdateMyContactData = {
    requestBody?: Body_profiles_update_my_contact;
};

export type ProfilesUpdateMyContactResponse = (ProfileWithContact);

export type ProfilesSetHomeStoreData = {
    requestBody: HomeStoreBody;
};

export type ProfilesSetHomeStoreResponse = (StorePublic);

export type ProfilesUpsertMyCriteriaData = {
    requestBody: CriteriaUpdate;
};

export type ProfilesUpsertMyCriteriaResponse = (CriteriaPublic);

export type ProfilesAddMyPhotoData = {
    requestBody: PhotoCommit;
};

export type ProfilesAddMyPhotoResponse = (ProfileWithContact);

export type ProfilesRemoveMyPhotoData = {
    index: number;
};

export type ProfilesRemoveMyPhotoResponse = (ProfileWithContact);

export type ProfilesDeactivateMeResponse = (Message);

export type ProfilesReactivateMeResponse = (Message);

export type ProfilesCancelAccountRequestResponse = (Message);

export type SiteGetQualificationsResponse = (QualificationList);

export type SitePutQualificationsData = {
    requestBody: QualificationList;
};

export type SitePutQualificationsResponse = (QualificationList);

export type StoresListCitiesResponse = (CityList);

export type StoresListStoresData = {
    city?: (string | null);
    limit?: number;
    skip?: number;
};

export type StoresListStoresResponse = (StoreList);

export type StoresGetStoreData = {
    storeId: string;
};

export type StoresGetStoreResponse = (StorePublic);

export type UploadsUploadImageData = {
    formData: Body_uploads_upload_image;
};

export type UploadsUploadImageResponse = (UploadResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WechatWechatLoginData = {
    requestBody: WechatLoginRequest;
};

export type WechatWechatLoginResponse = (WechatLoginResponse);