// This file is auto-generated by @hey-api/openapi-ts

export type AdminContactRequestItem = {
    id: string;
    from_user_id: string;
    from_xy_code?: (string | null);
    from_gender?: (string | null);
    from_year?: (number | null);
    from_location?: (string | null);
    from_contact_wechat?: (string | null);
    from_contact_phone?: (string | null);
    to_user_id: string;
    to_xy_code?: (string | null);
    to_gender?: (string | null);
    to_year?: (number | null);
    to_location?: (string | null);
    to_contact_wechat?: (string | null);
    to_contact_phone?: (string | null);
    message?: (string | null);
    status: string;
    admin_note?: (string | null);
    handled_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type AdminContactRequestList = {
    items?: Array<AdminContactRequestItem>;
    total?: number;
};

export type AdminCriteriaItem = {
    user_id: string;
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    income?: (string | null);
    edu?: (string | null);
    marriage?: (string | null);
    house?: (string | null);
    note?: (string | null);
    origins?: Array<(string)>;
    locations?: Array<(string)>;
    progress?: number;
};

/**
 * 资料详情 + 择偶要求 (admin 视角, 含联系方式)
 */
export type AdminProfileDetail = {
    profile: AdminProfileItem;
    criteria?: (AdminCriteriaItem | null);
};

export type AdminProfileItem = {
    user_id: string;
    xy_code?: (string | null);
    openid?: (string | null);
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    edu?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    body_type?: (string | null);
    desc?: (string | null);
    photos?: Array<(string)>;
    contact_wechat?: (string | null);
    contact_phone?: (string | null);
    audit_status: string;
    audit_reason?: (string | null);
    progress?: number;
    likes?: number;
    hot?: number;
    viewed_count?: number;
    unlock_balance?: number;
    verified?: string;
    user_status?: string;
    last_active_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type AdminProfileList = {
    items?: Array<AdminProfileItem>;
    total?: number;
};

export type AdminUserBrief = {
    id: string;
    openid?: (string | null);
    xy_code?: (string | null);
    email?: (string | null);
    is_superuser?: boolean;
    unlock_balance?: number;
    status?: string;
    last_active_at?: (string | null);
    created_at: string;
};

export type AdminUserItem = {
    id: string;
    actor: string;
    xy_code?: (string | null);
    openid?: (string | null);
    email?: (string | null);
    full_name?: (string | null);
    is_superuser?: boolean;
    unlock_balance?: number;
    notify_enabled?: boolean;
    verified?: string;
    status?: string;
    last_active_at?: (string | null);
    created_at: string;
};

export type AdminUserList = {
    items?: Array<AdminUserItem>;
    total?: number;
};

export type AuditRequest = {
    approve?: boolean;
    reason?: (string | null);
};

export type Body_contacts_send_intent = {
    message?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_profiles_update_my_contact = {
    wechat?: (string | null);
    phone?: (string | null);
};

export type Body_uploads_upload_image = {
    file: (Blob | File);
};

export type ContactRequestBody = {
    target_user_id: string;
    message?: (string | null);
};

export type ContactRequestList = {
    items?: Array<ContactRequestPublic>;
    total?: number;
};

/**
 * 用户视角: 看自己提交过的申请
 */
export type ContactRequestPublic = {
    id: string;
    from_user_id: string;
    to_user_id: string;
    target_xy_code?: (string | null);
    message?: (string | null);
    status: string;
    admin_note?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ContactRequestResult = {
    request_id: string;
    balance: number;
    status: string;
    created_at: string;
};

export type CriteriaPublic = {
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    income?: (string | null);
    edu?: (string | null);
    marriage?: (string | null);
    house?: (string | null);
    note?: (string | null);
    id: string;
    user_id: string;
    origins?: Array<(string)>;
    locations?: Array<(string)>;
    progress?: number;
};

export type CriteriaUpdate = {
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    income?: (string | null);
    edu?: (string | null);
    marriage?: (string | null);
    house?: (string | null);
    note?: (string | null);
    origins?: (Array<(string)> | null);
    locations?: (Array<(string)> | null);
};

export type FavoriteBrief = {
    user_id: string;
    xy_code?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    location?: (string | null);
    photos?: Array<(string)>;
    starred_at: string;
};

export type FavoriteList = {
    items?: Array<FavoriteBrief>;
    total?: number;
};

export type FilterRequest = {
    gender?: (string | null);
    year_min?: (number | null);
    year_max?: (number | null);
    height_min?: (number | null);
    height_max?: (number | null);
    edu?: (Array<(string)> | null);
    income?: (Array<(string)> | null);
    marriage?: (Array<(string)> | null);
    region?: (Array<(string)> | null);
    job?: (Array<(string)> | null);
    has_house?: (Array<(string)> | null);
    cursor?: (string | null);
    limit?: number;
};

export type GrantBalanceRequest = {
    delta?: number;
    reason?: (string | null);
};

export type HandleRequestBody = {
    status: 'accepted' | 'rejected' | 'contacted' | 'closed';
    admin_note?: (string | null);
};

export type status = 'accepted' | 'rejected' | 'contacted' | 'closed';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IntentResponse = {
    intent_id: string;
    sent_at: string;
};

/**
 * 列表项 - 不含联系方式 / desc 截断
 */
export type MatchBrief = {
    user_id: string;
    xy_code?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    edu?: (string | null);
    income?: (string | null);
    location?: (string | null);
    origin?: (string | null);
    desc?: (string | null);
    photos?: Array<(string)>;
    likes?: number;
    hot?: number;
    starred?: boolean;
};

export type MatchDetailResponse = {
    profile: (ProfilePublic | ProfileWithContact);
    xy_code?: (string | null);
    unlocked?: boolean;
    starred?: boolean;
};

export type MatchListResponse = {
    items?: Array<MatchBrief>;
    next_cursor?: (string | null);
};

export type Message = {
    message: string;
};

export type NeighborResponse = {
    user_id?: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PhotoCommit = {
    file_url: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfileMeResponse = {
    profile?: (ProfilePublic | null);
    criteria?: (CriteriaPublic | null);
    has_profile?: boolean;
    has_criteria?: boolean;
};

export type ProfilePublic = {
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    edu?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    body_type?: (string | null);
    desc?: (string | null);
    id: string;
    user_id: string;
    photos?: Array<(string)>;
    audit_status?: string;
    progress?: number;
    likes?: number;
    hot?: number;
    viewed_count?: number;
};

/**
 * 允许部分更新
 */
export type ProfileUpdate = {
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    edu?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    body_type?: (string | null);
    desc?: (string | null);
};

/**
 * 已解锁/管理员视角, 含联系方式
 */
export type ProfileWithContact = {
    relation?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    height?: (number | null);
    edu?: (string | null);
    income?: (string | null);
    marriage?: (string | null);
    origin?: (string | null);
    location?: (string | null);
    hometown?: (string | null);
    job?: (string | null);
    has_house?: (string | null);
    has_car?: (string | null);
    body_type?: (string | null);
    desc?: (string | null);
    id: string;
    user_id: string;
    photos?: Array<(string)>;
    audit_status?: string;
    progress?: number;
    likes?: number;
    hot?: number;
    viewed_count?: number;
    contact_wechat?: (string | null);
    contact_phone?: (string | null);
};

export type StaffCreate = {
    email: string;
    name: string;
    is_active?: boolean;
    password: string;
};

export type StaffPublic = {
    email: string;
    name: string;
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type StaffsPublic = {
    items?: Array<StaffPublic>;
    total?: number;
};

export type StaffUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
    password?: (string | null);
};

export type StatsResponse = {
    total_users?: number;
    total_profiles?: number;
    pending_audits?: number;
    today_signups?: number;
};

export type ToggleResponse = {
    starred: boolean;
    total_likes: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UploadResponse = {
    url: string;
    filename: string;
    size: number;
};

/**
 * admin 创建账号 (邮箱密码)
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    xy_code?: (string | null);
    unlock_balance?: number;
    notify_enabled?: boolean;
    verified?: string;
};

/**
 * 邮箱自助注册
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VisitorBrief = {
    user_id: string;
    xy_code?: (string | null);
    gender?: (string | null);
    year?: (number | null);
    photos?: Array<(string)>;
    last_viewed_at: string;
};

export type VisitorList = {
    items?: Array<VisitorBrief>;
    total?: number;
};

/**
 * dev 登录: 直接传 fake openid, 用于 AppID 没配置时联调小程序
 */
export type WechatDevLoginRequest = {
    openid: string;
};

export type WechatLoginRequest = {
    code: string;
};

export type WechatLoginResponse = {
    access_token: string;
    token_type?: string;
    user: UserPublic;
    has_profile?: boolean;
    has_criteria?: boolean;
};

/**
 * 统一的"当前登录者"返回, 兼容 User (含 superuser) 和 Staff
 */
export type WhoAmI = {
    id: string;
    actor_type: string;
    email?: (string | null);
    name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    can_read_admin?: boolean;
    can_write_admin?: boolean;
};

export type AdminListProfilesData = {
    auditStatus?: 'all' | 'pending' | 'approved' | 'rejected';
    /**
     * 搜寻缘号 / 居住地 / desc
     */
    keyword?: (string | null);
    limit?: number;
    skip?: number;
};

export type AdminListProfilesResponse = (AdminProfileList);

export type AdminGetProfileDetailData = {
    userId: string;
};

export type AdminGetProfileDetailResponse = (AdminProfileDetail);

export type AdminAuditProfileData = {
    requestBody: AuditRequest;
    userId: string;
};

export type AdminAuditProfileResponse = (AdminProfileItem);

export type AdminGrantUnlockBalanceData = {
    requestBody: GrantBalanceRequest;
    userId: string;
};

export type AdminGrantUnlockBalanceResponse = (AdminUserBrief);

export type AdminBlockUserData = {
    userId: string;
};

export type AdminBlockUserResponse = (AdminUserBrief);

export type AdminUnblockUserData = {
    userId: string;
};

export type AdminUnblockUserResponse = (AdminUserBrief);

export type AdminAdminStatsResponse = (StatsResponse);

export type AdminListAdminUsersData = {
    actor?: 'all' | 'wx' | 'admin';
    keyword?: (string | null);
    limit?: number;
    skip?: number;
};

export type AdminListAdminUsersResponse = (AdminUserList);

export type AdminListStaffData = {
    limit?: number;
    skip?: number;
};

export type AdminListStaffResponse = (StaffsPublic);

export type AdminCreateStaffEndpointData = {
    requestBody: StaffCreate;
};

export type AdminCreateStaffEndpointResponse = (StaffPublic);

export type AdminUpdateStaffEndpointData = {
    requestBody: StaffUpdate;
    staffId: string;
};

export type AdminUpdateStaffEndpointResponse = (StaffPublic);

export type AdminDeleteStaffEndpointData = {
    staffId: string;
};

export type AdminDeleteStaffEndpointResponse = (Message);

export type AdminListContactRequestsData = {
    limit?: number;
    skip?: number;
    status?: 'all' | 'pending' | 'accepted' | 'rejected' | 'contacted' | 'closed';
};

export type AdminListContactRequestsResponse = (AdminContactRequestList);

export type AdminHandleContactRequestData = {
    requestBody: HandleRequestBody;
    requestId: string;
};

export type AdminHandleContactRequestResponse = (AdminContactRequestItem);

export type ContactsSubmitContactRequestData = {
    requestBody: ContactRequestBody;
};

export type ContactsSubmitContactRequestResponse = (ContactRequestResult);

export type ContactsListMyContactRequestsData = {
    limit?: number;
    skip?: number;
};

export type ContactsListMyContactRequestsResponse = (ContactRequestList);

export type ContactsUnlockContactDeprecatedData = {
    targetId: string;
};

export type ContactsUnlockContactDeprecatedResponse = (unknown);

export type ContactsSendIntentData = {
    requestBody?: Body_contacts_send_intent;
    targetId: string;
};

export type ContactsSendIntentResponse = (IntentResponse);

export type FavoritesToggleFavoriteData = {
    targetId: string;
};

export type FavoritesToggleFavoriteResponse = (ToggleResponse);

export type FavoritesListMyFavoritesData = {
    limit?: number;
    skip?: number;
};

export type FavoritesListMyFavoritesResponse = (FavoriteList);

export type FavoritesListVisitorsData = {
    limit?: number;
    skip?: number;
};

export type FavoritesListVisitorsResponse = (VisitorList);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginWhoamiResponse = (WhoAmI);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MatchesGetDailyRecommendationsData = {
    cursor?: (string | null);
    limit?: number;
    tab?: 'today' | 'new' | 'missed';
};

export type MatchesGetDailyRecommendationsResponse = (MatchListResponse);

export type MatchesApplyFilterData = {
    requestBody: FilterRequest;
};

export type MatchesApplyFilterResponse = (MatchListResponse);

export type MatchesGetProfileDetailData = {
    userId: string;
};

export type MatchesGetProfileDetailResponse = (MatchDetailResponse);

export type MatchesGetNeighborData = {
    direction?: 'prev' | 'next';
    userId: string;
};

export type MatchesGetNeighborResponse = (NeighborResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfilesReadMyProfileResponse = (ProfileMeResponse);

export type ProfilesUpsertMyProfileData = {
    requestBody: ProfileUpdate;
};

export type ProfilesUpsertMyProfileResponse = (ProfilePublic);

export type ProfilesDeleteMyProfileResponse = (Message);

export type ProfilesUpdateMyContactData = {
    requestBody?: Body_profiles_update_my_contact;
};

export type ProfilesUpdateMyContactResponse = (ProfilePublic);

export type ProfilesUpsertMyCriteriaData = {
    requestBody: CriteriaUpdate;
};

export type ProfilesUpsertMyCriteriaResponse = (CriteriaPublic);

export type ProfilesAddMyPhotoData = {
    requestBody: PhotoCommit;
};

export type ProfilesAddMyPhotoResponse = (ProfilePublic);

export type ProfilesRemoveMyPhotoData = {
    index: number;
};

export type ProfilesRemoveMyPhotoResponse = (ProfilePublic);

export type UploadsUploadImageData = {
    formData: Body_uploads_upload_image;
};

export type UploadsUploadImageResponse = (UploadResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WechatWechatLoginData = {
    requestBody: WechatLoginRequest;
};

export type WechatWechatLoginResponse = (WechatLoginResponse);

export type WechatWechatDevLoginData = {
    requestBody: WechatDevLoginRequest;
};

export type WechatWechatDevLoginResponse = (WechatLoginResponse);