// data.jsx — Mock candidates + session state for the prototype.

const CANDIDATES = [
  {
    id: '36830153',
    gender: '女',
    year: 1987,
    height: 163,
    residence: '德州',
    hometown: '天津',
    education: '小学/初中',
    occupation: '国企员工',
    income: '3-5万',
    marriage: '离异已育',
    housing: '有婚房',
    body: '适中',
    intro: '我家女儿，出生于87年，身高163厘米，学历小学/初中，目前居住在德州，职业国企员工。性格温和，善解人意，喜欢安静的生活。希望找一位稳重踏实、愿意共同经营家庭的伴侣。',
    requirements: {
      yearRange: '1982年-1987年',
      income: '不限',
      height: '170cm-188cm',
      housing: '不限',
      education: '中专/高中及以上',
      marriage: '离异未育',
      hometown: '德州',
      residence: '德州',
    },
    likes: 0,
    hot: 116,
    posted: '3天前',
    avatarTone: 'rose',
    initial: '晴',
  },
  {
    id: '31821616',
    gender: '女',
    year: 1991,
    height: 160,
    residence: '德州德城区',
    hometown: '德州',
    education: '小学/初中',
    occupation: '销售',
    income: '5-7万',
    marriage: '未婚',
    housing: '无婚房',
    body: '苗条',
    intro: '我家女儿，出生于91年，身高160厘米，学历小学/初中，目前居住在德州德城区，职业销售。开朗外向，工作勤勉，喜欢旅行和读书。',
    requirements: {
      yearRange: '1988年-1993年',
      income: '10万以上',
      height: '172cm-185cm',
      housing: '有婚房',
      education: '大专及以上',
      marriage: '未婚',
      hometown: '不限',
      residence: '德州',
    },
    likes: 12,
    hot: 203,
    posted: '1天前',
    avatarTone: 'sage',
    initial: '悦',
  },
  {
    id: '42917283',
    gender: '男',
    year: 1985,
    height: 178,
    residence: '济南',
    hometown: '济南',
    education: '本科',
    occupation: '工程师',
    income: '15-20万',
    marriage: '未婚',
    housing: '有婚房',
    body: '匀称',
    intro: '本人出生于85年，身高178厘米，本科学历，目前在济南从事工程师工作。踏实可靠，生活规律，业余时间喜欢登山和摄影。',
    requirements: {
      yearRange: '1986年-1992年',
      income: '不限',
      height: '158cm-172cm',
      housing: '不限',
      education: '本科及以上',
      marriage: '未婚',
      hometown: '不限',
      residence: '济南',
    },
    likes: 45,
    hot: 418,
    posted: '今天',
    avatarTone: 'ocean',
    initial: '致',
  },
  {
    id: '58392014',
    gender: '男',
    year: 1982,
    height: 175,
    residence: '北京朝阳区',
    hometown: '保定',
    education: '硕士',
    occupation: '医生',
    income: '20万以上',
    marriage: '离异未育',
    housing: '有婚房',
    body: '适中',
    intro: '我儿子，出生于82年，身高175厘米，硕士学历，在北京朝阳区一家三甲医院工作。性格成熟稳重，对家庭观念重，希望找一位温柔体贴的伴侣共度余生。',
    requirements: {
      yearRange: '1983年-1990年',
      income: '不限',
      height: '160cm-172cm',
      housing: '不限',
      education: '本科及以上',
      marriage: '未婚 / 离异未育',
      hometown: '不限',
      residence: '北京',
    },
    likes: 88,
    hot: 512,
    posted: '2天前',
    avatarTone: 'indigo',
    initial: '朗',
  },
  {
    id: '23984105',
    gender: '女',
    year: 1993,
    height: 165,
    residence: '上海浦东',
    hometown: '苏州',
    education: '本科',
    occupation: '设计师',
    income: '10-15万',
    marriage: '未婚',
    housing: '无婚房',
    body: '苗条',
    intro: '我家女儿，93年出生，身高165厘米，本科学历，目前在上海从事设计工作。性格温婉，爱好烘焙、旅行和瑜伽，希望找到懂生活、懂尊重的另一半。',
    requirements: {
      yearRange: '1988年-1993年',
      income: '15万以上',
      height: '172cm-185cm',
      housing: '有婚房',
      education: '本科及以上',
      marriage: '未婚',
      hometown: '不限',
      residence: '上海',
    },
    likes: 134,
    hot: 672,
    posted: '今天',
    avatarTone: 'plum',
    initial: '雅',
  },
];

const EXPERIENCES = [
  {
    id: 'e1',
    title: '相亲第一面，聊什么最稳妥？',
    excerpt: '见面时不用急着聊房子车子，先从生活细节聊起——周末怎么过、家里常做什么菜，这些细节更能看出性格。',
    author: '老槐树下',
    tag: '经验',
    likes: 328,
    replies: 42,
  },
  {
    id: 'e2',
    title: '做父母的，给孩子相亲的三条原则',
    excerpt: '第一，尊重孩子的选择；第二，多看人品少看条件；第三，该放手时就放手。',
    author: '北京张阿姨',
    tag: '父母视角',
    likes: 512,
    replies: 89,
  },
  {
    id: 'e3',
    title: '异地恋能不能走到最后？',
    excerpt: '三年异地的我们，上周领了证。回头看，靠的不是技巧，是两个人都愿意为彼此调整节奏。',
    author: '阿琛',
    tag: '亲历',
    likes: 201,
    replies: 37,
  },
];

const MESSAGES = [
  { id: 'm1', name: '寻缘号 42917283', initial: '致', tone: 'ocean', preview: '您好，看了您家女儿的资料，觉得挺合适的', time: '刚刚', unread: 2 },
  { id: 'm2', name: '红娘 · 小李', initial: '李', tone: 'rose', preview: '为您推荐了 3 位新的对象，请查看', time: '2小时前', unread: 0, official: true },
  { id: 'm3', name: '寻缘号 58392014', initial: '朗', tone: 'indigo', preview: '谢谢您的联系，方便加个微信吗？', time: '昨天', unread: 0 },
  { id: 'm4', name: '系统通知', initial: '通', tone: 'ink', preview: '您的资料审核已通过', time: '3天前', unread: 0, official: true },
];

const CITIES = ['北京', '上海', '天津', '济南', '德州', '青岛', '苏州', '杭州', '成都', '西安', '广州', '深圳', '武汉', '长沙'];

Object.assign(window, { CANDIDATES, EXPERIENCES, MESSAGES, CITIES });
